project:
  type: website
  output-dir: docs

website:
  title: "visage"
  search: true
  reader-mode: true
  repo-url: "https://github.com/Aditya-Dahiya/visage"
  repo-actions: [edit, issue]
  site-url: "https://aditya-dahiya.github.io/visage/index.html"
  description: "Visualizing Information and Spatial Analysis with ggplot2 Extensions"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Geo-Computation"
        file: geocomputation.qmd
      - text: "ggplot2 Extensions"
        file: ggplot2_ext.qmd
      - text: "About"
        file: about.qmd 
    logo: "aditya-dahiya.jpg"
    logo-alt: "visage"
    tools:
      - icon: rss
        href: index.xml
      - icon: github
        menu:
          - text: "Source Code"
            url:  https://github.com/Aditya-Dahiya/visage
          - text: "Suggestions / Feedback"
            url:  https://github.com/Aditya-Dahiya/visage/issues

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

comments:
  giscus: 
    repo: Aditya-Dahiya/visage


